### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by nocmt** [rekols/rekols-dictionary#2]
./main.cpp:3:23: fatal error: DWidgetUtil: 没有那个文件或目录
 #include <DWidgetUtil>
                       ^
compilation terminated.
Makefile:502: recipe for target 'main.o' failed
make: *** [main.o] Error 1

**Comment by rekols** [comment]
你需要一个最新ｄｔｋ

**Comment by rekols** [comment]
编译教程：

https://github.com/rekols/developer/wiki/%E6%95%99%E4%BD%A0%E5%A6%82%E4%BD%95%E7%BC%96%E8%AF%91%E5%B9%B6%E6%89%93%E5%8C%85%E6%9C%80%E6%96%B0%E7%9A%84DTK
